{"name": "test_sum_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_1.Test_credence_1 object at 0x000001A6BE803190>\n\n       def test_sum_2(self):\n           a=10\n           b=9\n           sum = a+b\n           print(\"\\nSum of a & b is:\", sum)\n    #       print(\"\\nSum of a & b is:\",str(sum))\n           if sum==25:\n               assert True\n           else:\n               print(\"Sum is wrong, calculate it one more time\")\n>              assert False\nE              assert False\n\nTestCases\\test_file_1.py:54: AssertionError"}, "attachments": [{"name": "stdout", "source": "369061de-111d-485a-82f6-5317fd8145b1-attachment.txt", "type": "text/plain"}], "start": 1691062274055, "stop": 1691062274055, "uuid": "c300b21d-7073-4ebe-96f2-0647d59f80a6", "historyId": "b90bed3bfe9e48501b40b32300eac1a3", "testCaseId": "b90bed3bfe9e48501b40b32300eac1a3", "fullName": "TestCases.test_file_1.Test_credence_1#test_sum_2", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_file_1"}, {"name": "subSuite", "value": "Test_credence_1"}, {"name": "host", "value": "DESKTOP-4S5PPQ4"}, {"name": "thread", "value": "62744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_file_1"}]}